-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(HALF.TOTAL_ORDER) AS TOTAL_ORDER
FROM  FIRST_HALF AS HALF JOIN ICECREAM_INFO AS INFO ON INFO.FLAVOR=HALF.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY HALF.TOTAL_ORDER;